//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComportWriteInBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMDataBase
    {
        public string Part { get; set; }
        public string Descr { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> Last_accesed { get; set; }
    }
}
